---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex # This is created below
      containers:
      - image: quay.io/dexidp/dex:v2.26.0 #or quay.io/dexidp/dex:v2.26.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        
        ports:
        - name: https
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/ssl/certs

        env:
        - name: KUBERNETES_POD_NAMESPACE
          value: "dex"
          
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        hostPath:
            path: /etc/kubernetes/yaml/ssl
            type: Directory
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex
data:
  config.yaml: |
apiVersion: v1
kind: ConfigMap
metadata:   
  name: dex
  namespace: dex
data:
  config.yaml: |
    issuer: https://DOMINIO_DO_SERVIDOR_OU_IP:32001
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/ssl/certs/cert.pem
      tlsKey: /etc/ssl/certs/key.pem
    staticClients:
    - id: kubernetes
      redirectURIs:
      - 'https://DOMINIO_DO_SERVIDOR_OU_IP:32045/oauth2/callback'
      name: 'kubernetes'
      secret: 'dex'
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: DOMINIO OU IP DO AD
        insecureNoSSL: true
        insecureSkipVerify: false
        startTLS: false
        bindDN: 'USUÁRIO COM PERMISSÃO DE BIND DO AD'
        bindPW: 'SENHA DO USUÁRIO COM PERMISSÃO DE BIND'
        userSearch:
          baseDN: cn=Users,dc=example,dc=com
          filter: "(objectClass=person)"
          username: userPrincipalName
          idAttr: DN
          emailAttr: userPrincipalName
          nameAttr: cn
        groupSearch:
          baseDN: cn=grupo,ou=divisão,dc=example,dc=com
          filter: "(objectClass=group)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
    oauth2:
      skipApprovalScreen: true
      responseTypes: ["code","token","id_token"]
    logger:
      level: 'debug'
      format: 'text'
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
  type: NodePort
  ports:
  - name: https
    port: 5556
    protocol: TCP
    targetPort: 5556
    nodePort: 32001
  selector:
    app: dex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex           # Service account assigned to the dex pod, created above
  namespace: dex  # The namespace dex is running in
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authcodes.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: AuthCode
    listKind: AuthCodeList
    plural: authcodes
    singular: authcode
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authrequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: AuthRequest
    listKind: AuthRequestList
    plural: authrequests
    singular: authrequest
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oauth2clients.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: OAuth2Client
    listKind: OAuth2ClientList
    plural: oauth2clients
    singular: oauth2client
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: signingkeies.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: SigningKey
    listKind: SigningKeyList
    plural: signingkeies
    singular: signingkey
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: refreshtokens.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: RefreshToken
    listKind: RefreshTokenList
    plural: refreshtokens
    singular: refreshtoken
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Password
    listKind: PasswordList
    plural: passwords
    singular: password
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: offlinesessionses.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: OfflineSessions
    listKind: OfflineSessionsList
    plural: offlinesessionses
    singular: offlinesessions
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connectors.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: Connector
    listKind: ConnectorList
    plural: connectors
    singular: connector
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devicerequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: DeviceRequest
    listKind: DeviceRequestList
    plural: devicerequests
    singular: devicerequest
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devicetokens.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: DeviceToken
    listKind: DeviceTokenList
    plural: devicetokens
    singular: devicetoken
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
