apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --cookie-secure=false
        - --provider=oidc
        - --client-id=kubernetes
        - --client-secret=dex
        - --oidc-issuer-url=https://DOMINIO DO SERVIDOR OU IP:32001
        - --email-domain="*"
        - --ssl-insecure-skip-verify
        - --upstream=https://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
        - --redirect-url=https://DOMINIO DO SERVIDOR OU IP:32045
        - --https-address=0.0.0.0:8080
        - --reverse-proxy=true
        - --pass-basic-auth=false
        - --set-xauthrequest=true
        - --ssl-upstream-insecure-skip-verify=true
        - --pass-access-token=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --proxy-prefix=/oauth2
        - --cookie-refresh=1h
        - --cookie-expire=2h
        - --force-https=true
        - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
        - --tls-key-file=/etc/kubernetes/pki/apiserver.key
        - --scope=openid profile email groups
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: 29_b-4a-GgE_BFXMUpnURQ==
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
          
        volumeMounts:
        - name: tls
          mountPath: /etc/kubernetes/pki/
          
      volumes:
      - name: tls
        hostPath:
            path: /etc/kubernetes/pki/
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: dex
spec:
  ports:
  - name: https
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32045
  type: NodePort
  selector:
    k8s-app: oauth2-proxy
